version : '3.9'

services:
  gateway:
    container_name: gateway
    build:
      context: ./OuterAPI/LibraryOnContainers
      dockerfile: ./APIGateway/Dockerfile
    ports:
     - 5001:80
    depends_on:
     - mosquitto
     - data-service
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
  ekuiper:
    image: lfedge/ekuiper:1.5-slim
    container_name: ekuiper
    depends_on:
      - mosquitto
    ports:
      - "9081:9081"
    volumes:
      - ekuiper:/kuiper/data
  ekuiper-manager:
    image: emqx/ekuiper-manager:1.5
    container_name: ekuiper-manager
    ports:
      - "9082:9082"
  # Nodejs service
  data-service:
    container_name: nodejs
    build: ./InnerAPINode
    ports: 
      - "8080:8080"
    #dns:
      # - "8.8.8.8"  
    depends_on: 
      - mongo_db 
    environment:
      WAIT_HOSTS: mongo_db:27017  
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
      MONGODB_CONNSTRING: mongodb://mongo:27017/books
  
  #MongoDB service
  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    #dns:
      # - "8.8.8.8" 
    ports:
      - "27017:27017"
    volumes: 
      - mongo_db:/data/db

  #Analytics Node service
  analytics-service:
    container_name: analyticsNodeService
    build: ./AnalyticsMicroservice
    ports:
      - "5003:5003"
    depends_on:
     - mosquitto
     - influx_db  
     - notifications-service

  #InfluxDB service
  influx_db:
    container_name: influx-db
    image: influxdb:latest
    restart: always
    ports: 
      - "8086:8086"
    volumes: 
       - ./influxdb/data:/var/lib/influxdb
       - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
       - ./influxdb/init:/docker-entrypoint-initdb.d

  notifications-service:
    container_name: notifications-service
    build:
      context: ./OuterAPI/LibraryOnContainers
      dockerfile: ./NotificationsMicroservice/Dockerfile
    ports:
     - 50051:80

volumes:
  mongo_db: {}
  ekuiper: {}
  influx_db: {}
