version: '3.9'

services:

  #Node api container
    api:
      container_name: api_container    
      build : .
      ports: 
        - "8080:8080"
      #dns:
       # - "8.8.8.8"  
      depends_on: 
        - mongo_db 
      environment:
        WAIT_HOSTS: mongo_db:27017  
        WAIT_HOSTS_TIMEOUT: 300
        WAIT_SLEEP_INTERVAL: 30
        WAIT_HOST_CONNECT_TIMEOUT: 30
        MONGODB_CONNSTRING: mongodb://db_container:27017/books

    #MongoDB service
    mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      #dns:
       # - "8.8.8.8" 
      ports:
       - "27017:27017"
      volumes: 
        - mongo_db:/data/db

     

volumes:
  mongo_db: {}